name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy
        override: true

    - name: Install cspell
      run: npm install -g cspell

    - name: Install required cargo
      run: cargo install clippy-sarif sarif-fmt

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
      continue-on-error: true

    - name: Run rust-clippy
      run:
        cargo clippy
        --all-features
        --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
      continue-on-error: true

    - name: Upload analysis results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: rust-clippy-results.sarif
        wait-for-processing: true

    - name: Run Cspell
      run: cspell lint **/*.rs

    
